version: 2.1
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Updating System Dependencies
          command: npm install geckodriver --save-dev
      - run:
          name: Install API Dependencies
          command: npm run api:install
      - run:
          name: Install Frontend Dependencies
          command: npm run frontend:install && npm install chromedriver --save-dev
      - run:
          name: Run API Tests
          command: npm run api:test
      - run:
          name: Run Frontend Tests
          command: npm run frontend:test
