version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.4.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Updating System Dependencies
          command: npm install geckodriver --save-dev 

      # Install Node.js dependencies for API
      - run:
          name: Install API Dependencies
          command: npm run api:install

      # Install Node.js dependencies for Frontend
      - run:
          name: Install Frontend Dependencies
          command: npm run frontend:install && npm install i chromedriver --save -dev

      # Run API tests
      - run:
          name: Run API Tests
          command: npm run api:test

      # Run Frontend tests
      - run:
          name: Run Frontend Tests
          command: npm run frontend:test





  
